<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0cO52SE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0cO52SE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0cO52SE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0cO52SE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container0cO52SE\App_KernelDevDebugContainer([
    'container.build_hash' => '0cO52SE',
    'container.build_id' => '2b48f1db',
    'container.build_time' => 1710782051,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container0cO52SE');
